language: go
go: 1.5.1
install: go get -t -v ./...
sudo: false

addons:
  apt:
    packages:
    - libraptor2-dev
    - libmagic-dev

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/436c5c3b940207e4a069
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

